<?php /** @var \Dfe\Cms\Block $block */ ?>
<nav>
	<ul>
		<li class='logo'><a href='/'/></li>
		<li><a
			href='https://mage2.pro/c/extensions/stripe' target='_blank'
			title='Have a question or an issue? Post it here, and I will answer it.'
		>Community</a></li>
		<li><a
			href='customers' title='The list of websites are already using this extension.'
		>Customers</a></li>
		<li class='version'><a
			href='https://github.com/mage2pro/stripe/releases'
			target='_blank'
			title="Check the extension's version history."
		>v<?= df_github_repo_version('mage2pro/stripe'); ?></a></li>
	</ul>
</nav>
<h1>Stripe payment extension for Magento 2</h1>
The extension integrates your Magento 2 store with the <b><a href='https://stripe.com' target='_blank'>Stripe</a></b> payment service.
<br/>The source is on GitHub: <a href='https://github.com/mage2pro/stripe' target='_blank'>https://github.com/mage2pro/stripe</a>
<h2 id='installation'>Installation</h2>
<pre><code class='bash'>composer require mage2pro/stripe:*
bin/magento setup:upgrade
rm -rf pub/static/* && bin/magento setup:static-content:deploy &lt;locale, e.g.: en_GB&gt;
rm -rf var/di var/generation generated/code && bin/magento setup:di:compile
</code></pre>
<h2 id='settings'>Settings</h2>
<p>Open the «<b>Stores</b>» → «<b>Configuration</b>» section inside the Magento 2 backend.</p>
<img
	alt='The «Stores» → «Configuration» section in the Magento 2 backend'
	src='<?php echo $block->getViewFileUrl('Dfe_CmsStripe::i/magento-settings-stores-configuration.png')?>'
/>
<p>The Stripe extension settings are located in the «<b>Mage2.PRO</b>» → «<b>Payment</b>» → «<b>Stripe</b>» section.</p>
<img
	alt='The «Mage2.PRO» → «Payment» → «Stripe» section in the Magento 2 backend'
	src='<?php echo $block->getViewFileUrl('Dfe_CmsStripe::i/magento-settings-mage2.pro-payment-stripe.png')?>'
/>
<img
	alt='The «Stripe» extension settings in the Magento 2 backend'
	src='<?php echo $block->getViewFileUrl('Dfe_CmsStripe::i/stripe-magento-extension-settings.png')?>'
/>