<h1>Customers</h1>
<p>The list of Magento 2 based websites using this payment module.</p>
<script>require(['jquery', 'Df_Core/thirdParty/TableSorter/main'], function($) {$(function() {
	/**
	 * 2017-05-13
	 * sortList:
	 * «An array of instructions for per-column sorting and direction
	 * in the format: [[columnIndex, sortDirection], ... ]
	 * where columnIndex is a zero-based index for your columns left-to-right
	 * and sortDirection is 0 for Ascending and 1 for Descending.
	 * A valid argument that sorts ascending first by column 1 and then column 2
	 * looks like: [[0,0],[1,0]]»
	 * http://tablesorter.com/docs/
	 */
	$('.customers').tablesorter({sortList: [[0,0]]});
});});</script>
<table class='content customers'>
<thead><tr>
	<th><div class='text'>URL</div><div class='icon'><i/></div></th>
	<th><div class='text'>Country</div><div class='icon'><i/></div></th>
	<th><div class='text'>M2 Version</div><div class='icon'><i/></div></th>
	<th><div class='text'>M2 Edition</div><div class='icon'><i/></div></th>
</tr></thead>
<tbody>
<?=
df_cc_n(array_map(function(array $c) {
	/** @var string $iso2 */ $iso2 = $c['country'];
	/** @var string $url */ $url = $c['url'];
	/** @var array(string => string) $m */
	/** 2017-05-14 @todo df_magento_version_remote($url) is too slow. Maybe it should be run by Cron. */
	$m = dfa_select($c, ['version', 'edition']);
	return df_tag('tr', [], df_cc_n(
		df_tag('td', [], df_tag('a', ['href' => $url, 'target' => '_blank'], df_domain($url)))
		,df_tag('td', [], df_flag_span($iso2, $iso2))
		,df_tag('td', [], dfa($m, 'version'))
		,df_tag('td', [], dfa($m, 'edition'))
	));
}, df_module_json(dfe_portal_module_name(), 'customers')), df_flag_link(), df_fa_link())
?>
</tbody>
</table>
