<?php /** @var \Dfe\Portal\Block\Content $block */ ?>
<h1>Stripe payment extension for Magento 2</h1>
The extension integrates your Magento 2 store with the <b><a href='https://stripe.com' target='_blank'>Stripe</a></b> payment service.
<br/>The source is on GitHub: <a href='https://github.com/mage2pro/stripe' target='_blank'>https://github.com/mage2pro/stripe</a>
<h2 id='installation'>Installation</h2>
<pre><code class='bash'>composer require mage2pro/stripe:*
bin/magento setup:upgrade
rm -rf pub/static/* && bin/magento setup:static-content:deploy en_US &lt;additional locales, e.g.: de_DE&gt;
rm -rf var/di var/generation generated/code && bin/magento setup:di:compile
</code></pre>
<h2 id='settings'>Settings</h2>
See the <a href='settings'>manual</a>.