<?php /** @var \Dfe\Cms\Block\Content $block */ ?>
<h1>Stripe payment extension for Magento 2</h1>
The extension integrates your Magento 2 store with the <b><a href='https://stripe.com' target='_blank'>Stripe</a></b> payment service.
<br/>The source is on GitHub: <a href='https://github.com/mage2pro/stripe' target='_blank'>https://github.com/mage2pro/stripe</a>
<h2 id='installation'>Installation</h2>
<pre><code class='bash'>composer require mage2pro/stripe:*
bin/magento setup:upgrade
rm -rf pub/static/* && bin/magento setup:static-content:deploy &lt;locale, e.g.: en_GB&gt;
rm -rf var/di var/generation generated/code && bin/magento setup:di:compile
</code></pre>
<h2 id='settings'>Settings</h2>
<p>Open the «<b>Stores</b>» → «<b>Configuration</b>» section inside the Magento 2 backend.</p>
<?= $this->img(
	'magento-settings-stores-configuration.png'
	,'The «Stores» → «Configuration» section in the Magento 2 backend'
) ?>
<p>The Stripe extension settings are located in the «<b>Mage2.PRO</b>» → «<b>Payment</b>» → «<b>Stripe</b>» section.</p>
<?= $this->img(
	'magento-settings-mage2.pro-payment-stripe.png'
	,'The «Mage2.PRO» → «Payment» → «Stripe» section in the Magento 2 backend'
) ?>
<?= $this->img(
	'stripe-magento-extension-settings.png', 'The «Stripe» extension settings in the Magento 2 backend'
) ?>
<table class='settings'>
	<tbody>
		<tr>
			<td>Enable?</td>
			<td>Using this checkbox you can <b>enable</b> or <b>disable</b> the extension.</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>
		<tr>
			<td>STUB</td>
			<td>STUB</td>
		</tr>		
	</tbody>
</table>