<?php /** @var \Dfe\Portal\Block\Nav $block */ ?>
<nav>
	<ul>
		<li class='logo'><a href='/'/></li>
		<li><a href='settings' title='The extension settings.'>Settings</a></li>
		<li><a
			href='https://mage2.pro/c/stripe' target='_blank'
			title='Have a question or an issue? Post it here, and I will answer it.'
		>Community</a></li>
		<li><a
			href='customers' title='The list of websites are already using this extension.'
		>Customers</a></li>
		<li class='version'><a
			href='https://github.com/mage2pro/stripe/releases'
			target='_blank'
			title="Check the extension's version history."
		>v<?= df_github_repo_version('mage2pro/stripe'); ?></a></li>
	</ul>
</nav>